## Nba

- each domain in 2D includes some points
- each point like p has coordinates  p=(xp,yp)
- squre domain, $X\times Y=[0,1]\times [0,1]$

In [1]:
import numpy as np

In [8]:
x = np.linspace(0,1,10) 
y = np.linspace(0,1,10) 
print(x)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
M0 = np.zeros((10,10))

print(M0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
M0[4,1]

np.float64(0.0)

neighboorhood array
$B_{\epsilon}(p)$ = if $norm(y-p)<\epsilon$

In [13]:
for i in range(10):
    for j in range(10):
        if norm((Y[i,j]-(xp,yp)))<eps:
            Nba[p] = Y[i,j]

NameError: name 'norm' is not defined

- each point has a two coordinates, toalnnots[p]=(xp,yp)

- if we have 100 points in the domain, it means we 100 points!!

- our Nba has 100 rows, but the colomn of Nbd are different 